name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/grendlerpl/index.json
    - name: Build
      run:  dotnet build -c Release BackgroundQ.csproj
    - name: Pack
      run: dotnet pack --configuration Release --no-build --include-symbols -o ./
    - name: Publish
      run: dotnet nuget push BackgroundQ/bin/Release/*.nupkg --skip-duplicate
